In [1]:
# Derivatives of x², x³, sin(x) — compute them numerically (f(x+h) - f(x)) / h and verify against analytical
# Partial derivatives for f(x,y) = x²y + 3y
# Chain rule: z = sin(x²), verify dz/dx numerically
# Build a numerical_gradient(f, x) utility function — you'll reuse this all week

In [2]:
import numpy as np
# computing derivative as central difference
def numerical_derivative(f, x, h=1e-7):
    return (f(x + h) - f(x - h)) / (2 * h)

In [3]:
f = lambda x: x**2
print(f"f(x) = x^2 at x = 3: numerical = {numerical_derivative(f, 3):.6f}, analytical = {2 * 3}")

f(x) = x^2 at x = 3: numerical = 6.000000, analytical = 6


In [4]:
# forward difference is less accurate
def forward_derivative(f, x, h=1e-7):
    return (f(x + h) - f(x)) / h

f = lambda x: x**2
print(f"f(x) = x^2 at x = 3: numerical = {forward_derivative(f, 3):.6}")

f(x) = x^2 at x = 3: numerical = 6.0


In [5]:
a = np.array([1,2,3,4,5])

print("a:", a)
print("shape:", a.shape)
print("dtype:", a.dtype)

zeros = np.zeros(5)
ones = np.ones(3)
rng = np.arange(0, 10, 2) # starting from 0 to 10, 10 exclusive and separated by 2
lin = np.linspace(0, 1, 5) # [0, 0.25, 0.5. 0.75, 1.0] evenly spaced

print("zeros:", zeros)
print("ones:", ones)
print("range:", rng)
print("linear space:", lin)

a: [1 2 3 4 5]
shape: (5,)
dtype: int64
zeros: [0. 0. 0. 0. 0.]
ones: [1. 1. 1.]
range: [0 2 4 6 8]
linear space: [0.   0.25 0.5  0.75 1.  ]


In [6]:
prices = np.array([100, 200, 300, 400, 500])
print(prices * 2)
print(prices + 10)
print(prices ** 2)
print(np.sum(prices))
print(np.mean(prices))
print(np.max(prices))

[ 200  400  600  800 1000]
[110 210 310 410 510]
[ 10000  40000  90000 160000 250000]
1500
300.0
500


In [7]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print("a + b", a + b)
print("a * b", a * b)

m = np.array([[1,2,3],[4,5,6]])
print("shape:", m.shape)

print("mean of each col:", np.mean(m, axis=0)) # collapse rows
print("mean of each row:", np.mean(m, axis=1)) # collapse cols

a + b [11 22 33]
a * b [10 40 90]
shape: (2, 3)
mean of each col: [2.5 3.5 4.5]
mean of each row: [2. 5.]


In [8]:
A = np.array([[1,2],[3,4]])
B = np.array([5,6])

result = A @ B

print("A @ B", result)

W = np.array([[0.5, 0.3],
              [0.2, 0.8],
              [0.1, 0.4]])
x = np.array([10, 20])
b = np.array([1, 2, 3])

y = W @ x + b
print("y = Wx + b:", y)

f = lambda x: np.sin(x)
x = np.pi / 4
print(f"numerical derivative: {numerical_derivative(f, x):.6f}")

A @ B [17 39]
y = Wx + b: [12. 20. 12.]
numerical derivative: 0.707107


In [9]:
def numerical_gradient(f, params, h=1e-7):
    """Gradient of f wrt each element in params"""
    grad = np.zeros_like(params)
    for i in range(len(params)):
        old = params[i]

        params[i] = old + h
        loss_plus = f(params)

        params[i] = old - h
        loss_minus = f(params)

        grad[i] = (loss_plus - loss_minus) / (2 * h)
        params[i] = old

    return grad

def f(params):
    w, b = params[0], params[1]
    return w ** 2 + b ** 2

point = np.array([3.0, 2.0])
grad = numerical_gradient(f, point)

print(f"gradient: {grad}")
print(f"expected: [6.0, 4.0]")

gradient: [5.99999999 3.99999999]
expected: [6.0, 4.0]


In [10]:
X = np.array([1,2,3,4,5],dtype=float)
y = np.array([6,11,16,21,26],dtype=float)

def mse_loss(params):
    w, b = params[0], params[1]
    predictions = w * X + b
    return np.mean((predictions - y) ** 2)

w, b = 0.0, 0.0
lr = 0.01

print(f"Start: w={w:.3f}, b={b:.3f}, loss={mse_loss(np.array([w,b])):.3f}")

for step in range(1000):
    params = np.array([w, b])
    grad = numerical_gradient(mse_loss, params)

    w = w - lr * grad[0] # nudge w downhill
    b = b - lr * grad[1] # nudge b downhill

    if step % 40 == 0:
        loss = mse_loss(np.array([w,b]))
        print(f"Step {step:3d}: w={w:.3f}, b={b:.3f}, loss={loss:.3f}")

print(f"\nFinal: w{w:.3f}, b={b:.3f}")

Start: w=0.000, b=0.000, loss=306.000
Step   0: w=1.160, b=0.320, loss=178.331
Step  40: w=4.914, b=1.311, loss=0.018
Step  80: w=4.925, b=1.272, loss=0.013
Step 120: w=4.934, b=1.237, loss=0.010
Step 160: w=4.943, b=1.207, loss=0.008
Step 200: w=4.950, b=1.181, loss=0.006
Step 240: w=4.956, b=1.158, loss=0.005
Step 280: w=4.962, b=1.138, loss=0.003
Step 320: w=4.967, b=1.121, loss=0.003
Step 360: w=4.971, b=1.105, loss=0.002
Step 400: w=4.975, b=1.092, loss=0.002
Step 440: w=4.978, b=1.080, loss=0.001
Step 480: w=4.981, b=1.070, loss=0.001
Step 520: w=4.983, b=1.061, loss=0.001
Step 560: w=4.985, b=1.053, loss=0.001
Step 600: w=4.987, b=1.047, loss=0.000
Step 640: w=4.989, b=1.041, loss=0.000
Step 680: w=4.990, b=1.036, loss=0.000
Step 720: w=4.991, b=1.031, loss=0.000
Step 760: w=4.992, b=1.027, loss=0.000
Step 800: w=4.993, b=1.024, loss=0.000
Step 840: w=4.994, b=1.021, loss=0.000
Step 880: w=4.995, b=1.018, loss=0.000
Step 920: w=4.996, b=1.016, loss=0.000
Step 960: w=4.996, b=1.0